<?php

namespace App\Cli;

class Quotes
{
    public static function getRandomQuote()
    {

        $quotes = [
            "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
            "The way to get started is to quit talking and begin doing. - Walt Disney",
            "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
            "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
            "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
            "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
            "Life is what happens when you're busy making other plans. - John Lennon",
            "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
            "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt",
            "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
            "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
            "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
            "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
            "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
            "It is during our darkest moments that we must focus to see the light. - Aristotle",
            "Whoever is happy will make others happy too. - Anne Frank",
            "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
            "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
            "The only impossible journey is the one you never begin. - Tony Robbins",
            "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
            "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
            "Life is either a daring adventure or nothing at all. - Helen Keller",
            "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
            "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
            "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe",
            "The purpose of our lives is to be happy. - Dalai Lama",
            "Life is what happens when you're busy making other plans. - John Lennon",
            "Get busy living or get busy dying. - Stephen King",
            "You only live once, but if you do it right, once is enough. - Mae West",
            "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
            "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
            "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
            "Money and success don’t change people; they merely amplify what is already there. - Will Smith",
            "Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking. - Steve Jobs",
            "Not how long, but how well you have lived is the main thing. - Seneca",
            "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
            "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. - Henry Ford",
            "In order to write about life first you must live it. - Ernest Hemingway",
            "The big lesson in life, baby, is never be scared of anyone or anything. - Frank Sinatra",
            "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth. - (Attributed to various sources)",
            "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. - Leo Burnett",
            "Life is not a problem to be solved, but a reality to be experienced. - Soren Kierkegaard",
            "The unexamined life is not worth living. - Socrates",
            "Turn your wounds into wisdom. - Oprah Winfrey",
            "The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
            "Do all the good you can, for all the people you can, in all the ways you can, as long as you can. - Hillary Clinton",
            "Don’t settle for what life gives you; make life better and build something. - Ashton Kutcher",
            "Everything negative – pressure, challenges – is all an opportunity for me to rise. - Kobe Bryant",
            "I like criticism. It makes you strong. - LeBron James",
            "You never really learn much from hearing yourself speak. - George Clooney",
            "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this. - Celine Dion",
            "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty. - John F. Kennedy",
            "Live for each second without hesitation. - Elton John",
            "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
            "Life doesn’t require that we be the best, only that we try our best. - H. Jackson Brown Jr.",
            "You must expect great things of yourself before you can do them. - Michael Jordan",
            "The best way to predict your future is to create it. - Abraham Lincoln",
            "You cannot save people, you can just love them. - Anaïs Nin",
            "You only pass through this life once, you don’t come back for an encore. - Elvis Presley",
            "Be happy for this moment. This moment is your life. - Omar Khayyam",
            "Happiness is the feeling that power increases — that resistance is being overcome. - Friedrich Nietzsche",
            "I have learned to seek my happiness by limiting my desires, rather than in attempting to satisfy them. - John Stuart Mill",
            "The more man meditates upon good thoughts, the better will be his world and the world at large. - Confucius",
            "The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not. - Seneca",
            "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
            "When it is obvious that goals can’t be reached, don’t adjust the goals, but adjust the action steps. - Confucius",
            "There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you do. - Derek Jeter",
            "It’s hard to beat a person who never gives up. - Babe Ruth",
            "I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’ - Leah Busque",
            "If people are doubting how far you can go, go so far that you can’t hear them anymore. - Michele Ruiz",
            "We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success. - Arianna Huffington",
            "Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE. - Joss Whedon",
            "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
            "Life is about making an impact, not making an income. - Kevin Kruse",
            "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
            "We become what we think about. - Earl Nightingale",
            "A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power. - Brian Tracy",
            "You’re braver than you believe, and stronger than you seem, and smarter than you think. - A.A. Milne",
            "Learn as if you will live forever, live like you will die tomorrow. - Mahatma Gandhi",
            "When you change your thoughts, remember to also change your world. - Norman Vincent Peale",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "A goal is not always meant to be reached; it often serves simply as something to aim at. - Bruce Lee",
            "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
            "Success is not in what you have, but who you are. - Bo Bennett",
            "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
            "You are never too old to set another goal or to dream a new dream. - Les Brown",
            "If you can dream it, you can do it. - Walt Disney",
            "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
            "Act as if what you do makes a difference. It does. - William James",
            "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
            "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
            "The ones who are crazy enough to think they can change the world, are the ones that do. - Anonymous",
            "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
            "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
            "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
            "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don’t quit. - Conrad Hilton",
            "Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better. - Jim Rohn",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon"
        ];

        return $quotes[array_rand($quotes)];
    }
}
