#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Cli\MakeViewCommand;
use App\Cli\MakeModelCommand;
use App\Cli\MakeControllerCommand;
use App\Cli\ServeCommand;


$application = new Application();
$application->add(new ServeCommand());
$application->add(new MakeViewCommand());
$application->add(new MakeModelCommand());
$application->add(new MakeControllerCommand());

$application->run();
