#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Cli\MakeViewCommand;
use App\Cli\MakeModelCommand;
use App\Cli\MakeControllerCommand;
use App\Cli\ServeCommand;

$app = new Application();
$app->add(new ServeCommand());
$app->add(new MakeViewCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeControllerCommand());

$app->run();
